version: '3'

services:
  devcontainer:
    image: "mcr.microsoft.com/devcontainers/rust:1-1-bullseye"
    container_name: rustuploader
    volumes:
      - ..:/workspaces:cached
    networks:
      - dev_network
    command: sleep infinity

  mariadb:
    image: ispyb
    container_name: mariadb
    environment:
      MYSQL_DATABASE: ispyb
    ports:
      - "3306:3306"
    networks:
      - dev_network
networks:
  dev_network:
    driver: bridge